subscan-explorer/subscan-api-docs

source/includes/_general.md

waiting for https://github.com/itering/subscan-io/pull/968

docs: add extrinsic and events limit param

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prd.yml
.github/workflows/deploy-stg.yml

https://github.com/darwinia-network/crab-docs/pull/111

Vercel action

---

source/includes/_price.md

Add Networks Supported Token

---

source/includes/_para.md

waiting for feature testing up

Add parachain fund_timeline

---

source/includes/_evm.md

add trace_error_msg filed for /api/scan/evm/transaction

---

source/includes/_staking.md
source/includes/_v2.md

update param for reward_slash api

---

source/includes/_staking.md

add event_method field for reward_slash api

---

source/includes/_account.md
source/includes/_general.md
source/includes/_v2.md

- /api/v2/scan/search
- /api/scan/extrinsic add
- /api/scan/proxy/extrinsics

update api doc

---

source/includes/_account.md
source/includes/_general.md
source/includes/_v2.md

https://github.com/subscan-explorer/subscan/issues/403

add multisig api

---

source/includes/_general.md

update multisig api

---

source/includes/_general.md

support avgBlockTime for daily api

---

source/includes/_account.md
source/includes/_governance.md
source/includes/_v2.md

https://github.com/subscan-explorer/subscan/issues/2124

support referendum v2

---

source/includes/_account.md
source/includes/_general.md
source/includes/_governance.md
source/includes/_price.md
source/includes/_v2.md

https://github.com/subscan-explorer/subscan/issues/2140

add accounts/statistics api

---

source/includes/_v2.md

https://github.com/subscan-explorer/subscan/issues/2394

add transfer amount filter

---

source/includes/_account.md

https://github.com/subscan-explorer/subscan/issues/2420

add token holders api

---

source/includes/_evm.md

update transactions contract field

---

source/includes/_v2.md

add daily v2 api

---

source/includes/_account.md
source/includes/_v2.md

update account statistics api

---

source/includes/_general.md

https://github.com/subscan-explorer/subscan/issues/2527

support scan/multisigs/details api

---

source/includes/_account.md
source/includes/_general.md
source/includes/_v2.md

https://github.com/subscan-explorer/subscan/issues/2361

update account derive api

---

source/includes/_price.md

https://github.com/subscan-explorer/subscan/issues/2606

update price history price field

---

source/includes/_v2.md

https://github.com/subscan-explorer/subscan/issues/2452

add tracing state api

---

source/includes/_introduction.md

https://github.com/subscan-explorer/ui/pull/1484

chore: remove SNOW network

---

source/includes/_account.md

update accounts/statistics api

---

source/includes/_governance.md

update referenda/votes api

---

source/includes/_v2.md

#subscan-explorer/subscan/issues/2627

add data statistics api

---

source/includes/_account.md
source/includes/_governance.md
source/includes/_v2.md

update democracy api

---

source/includes/_governance.md

support preimage api

---

source/includes/_governance.md

update democracy/referenda votes api
